/** tech-news-agent scenarios — design §7.3. */
import type { Scenario } from "../engine/types";
import { PASSING_CONFIDENCE, RETRY_CONFIDENCE } from "./scene";

export const scenarios: Scenario[] = [
  {
    id: "run",
    label: "Run pipeline",
    steps: [
      { t: 0, kind: "set", target: "topic.text", value: "NVIDIA Blackwell GPU" },
      { t: 200, kind: "packet", edge: "topic-orch", duration: 700 },
      { t: 900, kind: "pulse", node: "orchestrator" },
      { t: 900, kind: "set", target: "orchestrator.spin", value: 1 },
      { t: 1200, kind: "packet", edge: "orch-scout", duration: 700 },
      { t: 1900, kind: "pulse", node: "scout" },
      { t: 2000, kind: "packet", edge: "scout-tavily", duration: 500 },
      { t: 2000, kind: "packet", edge: "scout-mcp", duration: 500 },
      { t: 2500, kind: "packet", edge: "tavily-scout", duration: 500 },
      { t: 2500, kind: "packet", edge: "mcp-scout", duration: 500 },
      { t: 3100, kind: "packet", edge: "scout-reporter", duration: 700 },
      { t: 3800, kind: "pulse", node: "reporter" },
      { t: 3800, kind: "set", target: "facts", value: 6 },
      { t: 4000, kind: "packet", edge: "reporter-editor", duration: 700 },
      { t: 4700, kind: "pulse", node: "editor" },
      { t: 4900, kind: "packet", edge: "editor-fact", duration: 700 },
      { t: 5600, kind: "pulse", node: "factchecker" },
      { t: 5600, kind: "set", target: "confidence", value: PASSING_CONFIDENCE },
      { t: 5600, kind: "say", text: "Fact check passed with confidence 0.83" },
      { t: 5900, kind: "packet", edge: "fact-writer", duration: 700 },
      { t: 6600, kind: "pulse", node: "writer" },
      { t: 6800, kind: "packet", edge: "writer-post", duration: 600 },
      { t: 7400, kind: "set", target: "post.ready", value: true },
      {
        t: 7400,
        kind: "say",
        text: "LinkedIn post written with HIGH, MEDIUM, and UNVERIFIED markers",
      },
    ],
    narration: [
      "The topic “NVIDIA Blackwell GPU” goes to the OrchestratorAgent, which starts its reason, act, observe loop.",
      "ScoutAgent gathers material through Tavily search and the GitHub MCP server.",
      "ReporterAgent extracts 6 facts and hands them to EditorAgent.",
      "FactCheckerAgent scores the result at 0.83, above the 0.6 threshold.",
      "LinkedInWriterAgent writes the post, marked up with [HIGH], [MEDIUM], and [UNVERIFIED] (example response from the README, about 63 seconds).",
    ],
  },
  {
    id: "retry",
    label: "Force a retry",
    steps: [
      { t: 0, kind: "set", target: "topic.text", value: "NVIDIA Blackwell GPU" },
      { t: 200, kind: "packet", edge: "topic-orch", duration: 700 },
      { t: 900, kind: "pulse", node: "orchestrator" },
      { t: 900, kind: "set", target: "orchestrator.spin", value: 1 },
      { t: 1200, kind: "packet", edge: "orch-scout", duration: 700 },
      { t: 1900, kind: "pulse", node: "scout" },
      { t: 2000, kind: "packet", edge: "scout-tavily", duration: 500 },
      { t: 2000, kind: "packet", edge: "scout-mcp", duration: 500 },
      { t: 2500, kind: "packet", edge: "tavily-scout", duration: 500 },
      { t: 2500, kind: "packet", edge: "mcp-scout", duration: 500 },
      { t: 3100, kind: "packet", edge: "scout-reporter", duration: 700 },
      { t: 3800, kind: "pulse", node: "reporter" },
      { t: 3800, kind: "set", target: "facts", value: 6 },
      { t: 4000, kind: "packet", edge: "reporter-editor", duration: 700 },
      { t: 4700, kind: "pulse", node: "editor" },
      { t: 4900, kind: "packet", edge: "editor-fact", duration: 700 },
      { t: 5600, kind: "pulse", node: "factchecker", tone: "fault" },
      { t: 5600, kind: "set", target: "confidence", value: RETRY_CONFIDENCE },
      { t: 5600, kind: "set", target: "confidence.illustrative", value: true },
      {
        t: 5600,
        kind: "say",
        text: "Fact check came back below the 0.6 threshold; the model decides to re-extract the facts",
      },
      {
        t: 5900,
        kind: "packet",
        edge: "fact-reporter",
        label: "re-extract facts",
        tone: "fault",
        duration: 900,
      },
      { t: 6800, kind: "pulse", node: "orchestrator" },
      { t: 6800, kind: "set", target: "orchestrator.spin", value: 2 },
      { t: 7000, kind: "pulse", node: "reporter" },
      { t: 7200, kind: "packet", edge: "reporter-editor", duration: 700 },
      { t: 7900, kind: "packet", edge: "editor-fact", duration: 700 },
      { t: 8600, kind: "pulse", node: "factchecker" },
      { t: 8600, kind: "set", target: "confidence", value: PASSING_CONFIDENCE },
      { t: 8600, kind: "set", target: "confidence.illustrative", value: false },
      { t: 8600, kind: "say", text: "The second pass passes with confidence 0.83" },
      { t: 8900, kind: "packet", edge: "fact-writer", duration: 700 },
      { t: 9600, kind: "pulse", node: "writer" },
      { t: 9800, kind: "packet", edge: "writer-post", duration: 600 },
      { t: 10400, kind: "set", target: "post.ready", value: true },
      {
        t: 10400,
        kind: "say",
        text: "LinkedIn post written with HIGH, MEDIUM, and UNVERIFIED markers",
      },
    ],
    narration: [
      "The topic goes to the OrchestratorAgent and the ReAct loop begins.",
      "ScoutAgent gathers material through Tavily and the GitHub MCP server; ReporterAgent extracts 6 facts.",
      "The first fact check falls below the 0.6 threshold (the failing figure shown here is illustrative; the README documents only the threshold and the passing score).",
      "The retry is the model's decision, not hardcoded Java: facts are re-extracted and the loop runs again.",
      "The second pass scores 0.83 and LinkedInWriterAgent writes the post with its [HIGH], [MEDIUM], and [UNVERIFIED] markers.",
    ],
  },
];
