/**
 * Salon Appointment System scenarios — the flows in PROJECT-OVERVIEW.md: §7.1
 * booking, §9 the exclusion constraint under a race, §7.2 reschedule, and the
 * §6 expiry worker. Endpoints, SQLSTATE, statuses and side effects are the
 * document's; nothing here is invented.
 */
import type { Scenario } from "../engine/types";

export const scenarios: Scenario[] = [
  {
    id: "book",
    label: "Book a slot",
    steps: [
      { t: 0, kind: "packet", edge: "a-next", label: "GET /availability", duration: 700 },
      { t: 700, kind: "packet", edge: "next-api", duration: 500 },
      { t: 1200, kind: "packet", edge: "api-db", label: "hours − time off − busy", duration: 800 },
      { t: 2000, kind: "packet", edge: "db-api", label: "[slot, slot…]", duration: 700 },
      {
        t: 2000,
        kind: "say",
        text: "Availability computed on demand: hours minus time off minus busy",
      },
      { t: 2700, kind: "packet", edge: "api-next", duration: 500 },
      { t: 3200, kind: "packet", edge: "next-a", duration: 600 },
      {
        t: 3800,
        kind: "packet",
        edge: "a-next",
        label: "POST /booking/otp/request",
        duration: 700,
      },
      { t: 4500, kind: "packet", edge: "next-api", duration: 500 },
      { t: 5000, kind: "packet", edge: "api-sms", duration: 600 },
      { t: 5600, kind: "packet", edge: "sms-a", label: "code", duration: 1000 },
      { t: 5600, kind: "say", text: "A one-time code is sent to the customer's phone" },
      { t: 6600, kind: "packet", edge: "a-next", label: "POST /booking/otp/verify", duration: 700 },
      { t: 7300, kind: "set", target: "cookie", value: true },
      { t: 7300, kind: "say", text: "Code verified: a remembered-phone cookie is set" },
      { t: 7500, kind: "packet", edge: "a-next", label: "POST /booking", duration: 700 },
      { t: 8200, kind: "packet", edge: "next-api", duration: 500 },
      { t: 8700, kind: "pulse", node: "api" },
      {
        t: 8700,
        kind: "say",
        text: "Phone from the cookie only, advisory lock, open-request cap, least-loaded stylist",
      },
      { t: 9000, kind: "packet", edge: "api-db", label: "INSERT + FLUSH", duration: 700 },
      { t: 9700, kind: "set", target: "constraint", value: "ok" },
      { t: 9700, kind: "status", node: "db", value: "REQUESTED" },
      { t: 9700, kind: "say", text: "The exclusion constraint admits the row: REQUESTED" },
      { t: 9900, kind: "packet", edge: "api-sms", label: "new request", duration: 600 },
      { t: 9900, kind: "packet", edge: "api-next", duration: 500 },
      { t: 10400, kind: "packet", edge: "next-a", label: "Pending", duration: 600 },
      { t: 10500, kind: "packet", edge: "sms-stylist", duration: 600 },
      { t: 11100, kind: "pulse", node: "stylist" },
      { t: 11400, kind: "packet", edge: "stylist-api", label: "approve", duration: 700 },
      { t: 12100, kind: "status", node: "db", value: "CONFIRMED" },
      {
        t: 12100,
        kind: "say",
        text: "The assigned stylist approves: CONFIRMED, reminders scheduled",
      },
      { t: 12300, kind: "packet", edge: "api-sms", duration: 600 },
      { t: 12900, kind: "packet", edge: "sms-a", label: "signed manage link", duration: 1000 },
      {
        t: 13900,
        kind: "say",
        text: "The confirmation carries a signed link to cancel or reschedule",
      },
    ],
    narration: [
      "The customer picks services, a stylist and a date. GET /availability computes working hours minus time off minus busy appointments; no slot table is stored.",
      "POST /booking/otp/request sends a one-time code by SMS, and POST /booking/otp/verify sets a remembered-phone cookie.",
      "POST /booking takes the phone from that cookie only, holds an advisory lock on salon and phone, checks the open-request cap, and resolves the least-loaded qualifying stylist.",
      "The row is inserted and flushed. The exclusion constraint admits it, and the appointment is REQUESTED; the customer sees Pending.",
      "The assigned stylist is notified by SMS and approves from the dashboard: CONFIRMED, with reminders scheduled.",
      "The confirmation carries a signed manage link, so the customer can cancel or reschedule without an account.",
    ],
  },
  {
    id: "race",
    label: "Two customers, one slot",
    steps: [
      { t: 0, kind: "packet", edge: "a-next", label: "POST /booking", duration: 700 },
      { t: 0, kind: "packet", edge: "b-next", label: "POST /booking", duration: 700 },
      { t: 700, kind: "packet", edge: "next-api", duration: 500 },
      { t: 700, kind: "packet", edge: "next-api", duration: 500 },
      { t: 1200, kind: "set", target: "check.A", value: true },
      { t: 1200, kind: "set", target: "check.B", value: true },
      { t: 1200, kind: "say", text: "Both requests pass the application's availability check" },
      { t: 1400, kind: "packet", edge: "api-db", label: "INSERT + FLUSH", duration: 700 },
      { t: 1700, kind: "packet", edge: "api-db", label: "INSERT + FLUSH", duration: 700 },
      { t: 2100, kind: "set", target: "constraint", value: "ok" },
      { t: 2100, kind: "status", node: "db", value: "REQUESTED" },
      { t: 2100, kind: "say", text: "The first insert is admitted: REQUESTED" },
      { t: 2400, kind: "pulse", node: "db", tone: "fault" },
      { t: 2400, kind: "set", target: "constraint", value: "blocked" },
      {
        t: 2400,
        kind: "say",
        text: "The second overlaps it, and the exclusion constraint refuses the row",
      },
      { t: 2600, kind: "packet", edge: "db-api", label: "23P01", tone: "fault", duration: 600 },
      {
        t: 3200,
        kind: "packet",
        edge: "api-next",
        label: "409 SLOT_CONFLICT",
        tone: "fault",
        duration: 600,
      },
      { t: 3800, kind: "packet", edge: "next-b", tone: "fault", duration: 600 },
      { t: 4400, kind: "set", target: "conflict.B", value: true },
      {
        t: 4400,
        kind: "say",
        text: "SQLSTATE 23P01 is returned to the second customer as 409 SLOT_CONFLICT",
      },
    ],
    narration: [
      "Two customers tap the same slot at the same moment.",
      "Both requests pass the application's availability check, because neither has committed when the other checks.",
      "Both inserts reach PostgreSQL. The GiST exclusion constraint admits the first: REQUESTED.",
      "The second overlaps it and fails with SQLSTATE 23P01, translated narrowly into 409 SLOT_CONFLICT.",
      "The database, not the application, decided who got the slot.",
    ],
  },
  {
    id: "reschedule",
    label: "Reschedule",
    steps: [
      { t: 0, kind: "set", target: "original", value: "CONFIRMED" },
      { t: 0, kind: "say", text: "The original appointment is CONFIRMED and holds its slot" },
      {
        t: 300,
        kind: "packet",
        edge: "a-next",
        label: "…/{token}/reschedule",
        duration: 800,
      },
      { t: 1100, kind: "packet", edge: "next-api", duration: 500 },
      { t: 1600, kind: "packet", edge: "api-db", label: "INSERT new row", duration: 700 },
      { t: 2300, kind: "set", target: "replacement", value: "REQUESTED" },
      {
        t: 2300,
        kind: "say",
        text: "A new REQUESTED row points at the original, which stays CONFIRMED",
      },
      { t: 2500, kind: "packet", edge: "api-sms", label: "new request", duration: 600 },
      { t: 3100, kind: "packet", edge: "sms-stylist", duration: 600 },
      { t: 3700, kind: "pulse", node: "stylist" },
      { t: 4000, kind: "packet", edge: "stylist-api", label: "approve", duration: 700 },
      { t: 4700, kind: "set", target: "replacement", value: "CONFIRMED" },
      { t: 4700, kind: "set", target: "original", value: "CANCELLED" },
      {
        t: 4700,
        kind: "say",
        text: "Approved: the replacement is CONFIRMED and the original is CANCELLED, silently",
      },
      { t: 4900, kind: "packet", edge: "api-sms", duration: 600 },
      { t: 5500, kind: "packet", edge: "sms-a", label: "new manage link", duration: 900 },
      { t: 6400, kind: "say", text: "The confirmation carries a new manage link" },
    ],
    narration: [
      "The original appointment is CONFIRMED and holds its slot.",
      "The customer opens the signed manage link and picks a new time: POST /api/manage/{token}/reschedule.",
      "A new REQUESTED row is inserted with replaces_appointment_id pointing at the original, which is not touched.",
      "The assigned stylist approves the replacement. It becomes CONFIRMED, and the original is CANCELLED silently, its reminders with it.",
      "Had nobody approved, the replacement would have expired and the original booking would stand.",
    ],
  },
  {
    id: "expire",
    label: "Nobody approves",
    steps: [
      { t: 0, kind: "status", node: "db", value: "REQUESTED" },
      { t: 0, kind: "say", text: "A request is waiting for the assigned stylist" },
      { t: 600, kind: "pulse", node: "worker" },
      { t: 900, kind: "packet", edge: "worker-db", label: "conditional UPDATE", duration: 800 },
      { t: 1700, kind: "status", node: "db", value: "EXPIRED", tone: "idle" },
      { t: 1700, kind: "set", target: "silent", value: true },
      {
        t: 1700,
        kind: "say",
        text: "Expired and the slot released, deliberately without messaging anyone",
      },
    ],
    narration: [
      "A request that nobody actions would otherwise hold its slot forever.",
      "The expiry worker runs every 60 seconds and moves stale requests from REQUESTED to EXPIRED with a conditional update.",
      "It is deliberately silent: the slot is released without messaging the customer.",
    ],
  },
];
