/**
 * Salon Appointment System scene. A private client project, so every name here
 * comes from its PROJECT-OVERVIEW.md: the two browsers and the stylist from §2
 * Roles, Next.js / Spring Boot / PostgreSQL / the SMS gateway from §1 and §3,
 * BookingService and the 60s expiry worker from §6, btree_gist from §1. See
 * docs/readme-trace.md.
 */
import type { Scene } from "../engine/types";

/** §6 — the happy path, then the states that end it early. */
export const STATE_PATH = ["REQUESTED", "CONFIRMED", "COMPLETED"] as const;
export const STATE_EXITS = ["DECLINED", "EXPIRED", "CANCELLED", "NO_SHOW"] as const;

export const scene: Scene = {
  viewBox: [720, 400],
  nodes: [
    {
      id: "customerA",
      label: "Customer",
      sub: "no account",
      x: 16,
      y: 36,
      w: 124,
      h: 40,
      kind: "client",
    },
    {
      id: "customerB",
      label: "Customer",
      sub: "same slot",
      x: 16,
      y: 166,
      w: 124,
      h: 40,
      kind: "client",
    },
    {
      id: "next",
      label: "Next.js 16",
      sub: "App Router",
      x: 190,
      y: 100,
      w: 128,
      h: 40,
      kind: "service",
    },
    {
      id: "api",
      label: "Spring Boot 4.1",
      sub: "BookingService",
      x: 368,
      y: 100,
      w: 152,
      h: 40,
      kind: "service",
    },
    { id: "sms", label: "SMS gateway", x: 568, y: 36, w: 136, h: 36, kind: "tool" },
    {
      id: "stylist",
      label: "Stylist",
      sub: "dashboard",
      x: 568,
      y: 166,
      w: 136,
      h: 40,
      kind: "client",
    },
    {
      id: "db",
      label: "PostgreSQL 16",
      sub: "btree_gist",
      x: 368,
      y: 226,
      w: 152,
      h: 40,
      kind: "store",
    },
    {
      id: "worker",
      label: "expiry worker",
      sub: "@60s",
      x: 568,
      y: 226,
      w: 136,
      h: 40,
      kind: "stage",
    },
  ],
  edges: [
    { id: "a-next", from: "customerA", to: "next" },
    { id: "next-a", from: "next", to: "customerA" },
    { id: "b-next", from: "customerB", to: "next" },
    { id: "next-b", from: "next", to: "customerB" },
    { id: "next-api", from: "next", to: "api" },
    { id: "api-next", from: "api", to: "next" },
    { id: "api-db", from: "api", to: "db" },
    { id: "db-api", from: "db", to: "api" },
    { id: "api-sms", from: "api", to: "sms" },
    { id: "sms-a", from: "sms", to: "customerA" },
    { id: "sms-stylist", from: "sms", to: "stylist" },
    { id: "stylist-api", from: "stylist", to: "api" },
    { id: "worker-db", from: "worker", to: "db" },
  ],
  // Two columns, customers on top: every edge is a straight run except the
  // two that cross in the gap under the customers.
  narrow: {
    viewBox: [360, 490],
    nodes: [
      {
        id: "customerA",
        label: "Customer",
        sub: "no account",
        x: 12,
        y: 44,
        w: 150,
        h: 40,
        kind: "client",
      },
      {
        id: "customerB",
        label: "Customer",
        sub: "same slot",
        x: 198,
        y: 44,
        w: 150,
        h: 40,
        kind: "client",
      },
      {
        id: "next",
        label: "Next.js 16",
        sub: "App Router",
        x: 12,
        y: 128,
        w: 150,
        h: 40,
        kind: "service",
      },
      { id: "sms", label: "SMS gateway", x: 198, y: 130, w: 150, h: 36, kind: "tool" },
      {
        id: "api",
        label: "Spring Boot 4.1",
        sub: "BookingService",
        x: 12,
        y: 212,
        w: 150,
        h: 40,
        kind: "service",
      },
      {
        id: "stylist",
        label: "Stylist",
        sub: "dashboard",
        x: 198,
        y: 212,
        w: 150,
        h: 40,
        kind: "client",
      },
      {
        id: "db",
        label: "PostgreSQL 16",
        sub: "btree_gist",
        x: 12,
        y: 300,
        w: 150,
        h: 40,
        kind: "store",
      },
      {
        id: "worker",
        label: "expiry worker",
        sub: "@60s",
        x: 198,
        y: 300,
        w: 150,
        h: 40,
        kind: "stage",
      },
    ],
  },
};
