/**
 * Order-Saga scenarios — the step tables in design §7.1, which follow the
 * README's event flow. Topic names, statuses and the compensation behaviour are
 * the README's; nothing here is invented.
 */
import type { Scenario } from "../engine/types";

export const scenarios: Scenario[] = [
  {
    id: "place-order",
    label: "Place order",
    steps: [
      { t: 0, kind: "packet", edge: "gw-order", label: "POST /api/orders", duration: 700 },
      { t: 700, kind: "status", node: "order", value: "PENDING" },
      { t: 700, kind: "say", text: "Order created, status PENDING" },
      { t: 900, kind: "packet", edge: "order-inv", label: "order.created", duration: 1000 },
      { t: 1900, kind: "pulse", node: "inventory" },
      { t: 1900, kind: "set", target: "inventory.processed", value: 1 },
      { t: 2100, kind: "packet", edge: "inv-order", label: "inventory.reserved", duration: 1000 },
      { t: 2100, kind: "packet", edge: "inv-pay", label: "inventory.reserved", duration: 1000 },
      { t: 3100, kind: "status", node: "order", value: "INVENTORY_RESERVED" },
      { t: 3100, kind: "set", target: "order.processed", value: 1 },
      { t: 3100, kind: "pulse", node: "payment" },
      { t: 3100, kind: "set", target: "payment.processed", value: 1 },
      { t: 3400, kind: "packet", edge: "pay-out", label: "payment gateway", duration: 400 },
      { t: 3800, kind: "packet", edge: "pay-back", duration: 400 },
      { t: 4200, kind: "packet", edge: "pay-order", label: "payment.succeeded", duration: 1000 },
      { t: 4200, kind: "packet", edge: "pay-ship", label: "payment.succeeded", duration: 1000 },
      { t: 5200, kind: "status", node: "order", value: "PAYMENT_PROCESSING" },
      { t: 5200, kind: "set", target: "order.processed", value: 2 },
      { t: 5200, kind: "pulse", node: "shipping" },
      { t: 5200, kind: "set", target: "shipping.processed", value: 1 },
      { t: 5500, kind: "packet", edge: "ship-order", label: "shipment.created", duration: 1000 },
      { t: 5500, kind: "packet", edge: "ship-notif", label: "shipment.created", duration: 1000 },
      { t: 6500, kind: "status", node: "order", value: "COMPLETED", tone: "signal" },
      { t: 6500, kind: "set", target: "order.processed", value: 3 },
      { t: 6500, kind: "pulse", node: "notification" },
      { t: 6500, kind: "set", target: "notification.processed", value: 1 },
      {
        t: 6500,
        kind: "say",
        text: "Shipment created, order COMPLETED, notification sent",
      },
    ],
    narration: [
      "The gateway forwards POST /api/orders to the order service.",
      "Order is written with status PENDING and publishes order.created.",
      "Inventory consumes order.created, reserves stock, and publishes inventory.reserved.",
      "Order moves to INVENTORY_RESERVED; payment consumes the same event.",
      "Payment calls the mock payment provider and publishes payment.succeeded.",
      "Order moves to PAYMENT_PROCESSING; shipping consumes payment.succeeded.",
      "Shipping publishes shipment.created; order reaches COMPLETED and notification sends the confirmation.",
    ],
  },
  {
    id: "fail-payment",
    label: "Fail payment",
    steps: [
      { t: 0, kind: "packet", edge: "gw-order", label: "POST /api/orders", duration: 700 },
      { t: 700, kind: "status", node: "order", value: "PENDING" },
      { t: 700, kind: "say", text: "Order created, status PENDING" },
      { t: 900, kind: "packet", edge: "order-inv", label: "order.created", duration: 1000 },
      { t: 1900, kind: "pulse", node: "inventory" },
      { t: 1900, kind: "set", target: "inventory.processed", value: 1 },
      { t: 1900, kind: "set", target: "inventory.stock", value: "reserved" },
      { t: 2100, kind: "packet", edge: "inv-order", label: "inventory.reserved", duration: 1000 },
      { t: 2100, kind: "packet", edge: "inv-pay", label: "inventory.reserved", duration: 1000 },
      { t: 3100, kind: "status", node: "order", value: "INVENTORY_RESERVED" },
      { t: 3100, kind: "pulse", node: "payment" },
      { t: 3400, kind: "packet", edge: "pay-out", label: "payment gateway", duration: 400 },
      { t: 3800, kind: "packet", edge: "pay-back", tone: "fault", duration: 400 },
      {
        t: 4200,
        kind: "packet",
        edge: "pay-inv",
        label: "payment.failed",
        tone: "fault",
        duration: 1000,
      },
      {
        t: 4200,
        kind: "packet",
        edge: "pay-order",
        label: "payment.failed",
        tone: "fault",
        duration: 1000,
      },
      {
        t: 4200,
        kind: "packet",
        edge: "pay-notif",
        label: "payment.failed",
        tone: "fault",
        duration: 1000,
      },
      { t: 5200, kind: "status", node: "order", value: "COMPENSATING", tone: "fault" },
      { t: 5200, kind: "pulse", node: "inventory", tone: "fault" },
      { t: 5200, kind: "set", target: "inventory.stock", value: "released" },
      {
        t: 5200,
        kind: "say",
        text: "Payment failed; order is COMPENSATING and reserved inventory is released",
      },
      { t: 6200, kind: "status", node: "order", value: "FAILED", tone: "fault" },
      { t: 6200, kind: "pulse", node: "notification", tone: "fault" },
      {
        t: 6200,
        kind: "say",
        text: "Payment failed; inventory released; order FAILED; failure email sent",
      },
    ],
    narration: [
      "The gateway forwards POST /api/orders to the order service.",
      "Order is written with status PENDING and publishes order.created.",
      "Inventory reserves stock and publishes inventory.reserved.",
      "Payment calls the mock payment provider, which declines, and publishes payment.failed.",
      "Order moves to COMPENSATING and inventory releases the stock it had reserved.",
      "Order reaches FAILED and notification sends the failure email.",
    ],
  },
  {
    id: "out-of-stock",
    label: "Out of stock",
    steps: [
      { t: 0, kind: "packet", edge: "gw-order", label: "POST /api/orders", duration: 700 },
      { t: 700, kind: "status", node: "order", value: "PENDING" },
      { t: 700, kind: "say", text: "Order created, status PENDING" },
      { t: 900, kind: "packet", edge: "order-inv", label: "order.created", duration: 1000 },
      { t: 1900, kind: "pulse", node: "inventory", tone: "fault" },
      { t: 1900, kind: "set", target: "inventory.processed", value: 1 },
      {
        t: 2100,
        kind: "packet",
        edge: "inv-order",
        label: "inventory.failed",
        tone: "fault",
        duration: 1000,
      },
      {
        t: 2100,
        kind: "packet",
        edge: "inv-notif",
        label: "inventory.failed",
        tone: "fault",
        duration: 1000,
      },
      { t: 3100, kind: "status", node: "order", value: "FAILED", tone: "fault" },
      { t: 3100, kind: "pulse", node: "notification", tone: "fault" },
      {
        t: 3100,
        kind: "say",
        text: "Inventory unavailable; order FAILED; out-of-stock email sent",
      },
    ],
    narration: [
      "The gateway forwards POST /api/orders to the order service.",
      "Order is written with status PENDING and publishes order.created.",
      "Inventory cannot reserve the stock and publishes inventory.failed.",
      "Order reaches FAILED and notification sends the out-of-stock email.",
    ],
  },
];
